" Direction Key
"   i
" j   l
"   k
noremap i k
noremap j h
noremap k j
noremap h i
noremap U 5k
noremap M 5j

" Control
map S :w<CR>
map s <nop>
map Q :q<CR>
map R :source $MYVIMRC<CR>
map QF :q!<CR>
map <C-a> ggVG
map ol o<CR>
map OL O<CR>
map SQ :w<CR>:q<CR>

" View
syntax on
set number
set cursorline
set wrap
set showcmd
set wildmenu
set scrolloff=5

" Syntax
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
" set cindent
set ruler
inoremap ( ()<Esc>1i
inoremap [ []<Esc>1i
inoremap { {}<Esc>1i<CR><CR><Esc>ka
inoremap < <><Esc>1i
inoremap ' ''<Esc>1i
inoremap " ""<Esc>1i

" Search
set hlsearch
